"""Nombres de los documentos fuente del repositorio (para las notas del orador)."""
INS = "what-is-advanced-work-packaging-insight-awp.md"
OVR = "advanced-work-packaging-awp-overview.md"
OMG = "advanced-work-packaging-a-recommended-practice-for-capital-projects-omega-365-blogs.md"
COAA = "cop-awp-pbp-01-2016-v1-advanced-work-packaging-summary-pdf.md"
QS = "advanced-work-packaging-awp-quick-start-guide-pdf.md"
P1 = "1-advanced-work-packaging-procedure-insight-awp-2017-pdf.md"
P2 = "2-information-management-procedure-insight-awp-2017-pdf.md"
P3 = "3-workface-planning-procedure-insight-awp-2017-pdf.md"
PRI = "awp-education-primer-pdf.md"
FW = "cii-awp-cba-education-framework-pdf.md"
CUR = "awp-2023-integrado-pdf.md"
GLO = "awp-acronyms-definitions-pdf.md"
LC = "awp-vs-lc-pdf.md"
PPT = "AWP 2022 03 04.pptx.md"
IDX = "INDICE.md"
